# Generated by Django 4.1.2 on 2022-11-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Професія')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Професія',
                'verbose_name_plural': 'Професія',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unemployed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priz', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('pobat', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('nomer_phone', models.CharField(max_length=10)),
                ('special', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posada', models.CharField(max_length=255, verbose_name='Посада')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('firma', models.CharField(max_length=255, verbose_name='Фірма')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='Місто')),
                ('street', models.CharField(max_length=255, null=True, verbose_name='Вулиця')),
                ('vumogu', models.TextField(blank=True, verbose_name='Вимоги')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Умови праці')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата опублікування')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancies.profession', verbose_name='Професії')),
            ],
            options={
                'verbose_name': 'Вільні вакансії',
                'verbose_name_plural': 'Вільні вакансії',
                'ordering': ['-time_create'],
            },
        ),
    ]
