# Generated by Django 4.1.2 on 2022-11-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_unemployed_vc'),
    ]

    operations = [
        migrations.AddField(
            model_name='unemployed',
            name='us',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
