# Generated by Django 4.1.2 on 2022-11-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_remove_unemployed_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unemployed',
            options={'verbose_name': 'Безробітні', 'verbose_name_plural': 'Безробітні'},
        ),
        migrations.AddField(
            model_name='unemployed',
            name='em',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='salary',
            field=models.IntegerField(null=True, verbose_name='Заробітна плата'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='nomer_phone',
            field=models.CharField(max_length=10, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='pobat',
            field=models.CharField(max_length=100, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='priz',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='special',
            field=models.CharField(max_length=100, verbose_name='Спеціальність'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='year',
            field=models.IntegerField(verbose_name='Вік'),
        ),
    ]
